# This GitHub workflow runs on every commit.
# It runs the following checks:
# -

name: pull-request-checks

on:
  pull_request:

jobs:
  black:  # Check that source code is black-ified
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: 3.9

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: |
          black --check .
